create table if not exists authorizations (
  id bigint generated by default as identity primary key,
  authorization_id uuid not null,
  tenant_id uuid not null,
  patient_id text not null,
  operator_code text not null,
  status text not null,
  clinical_justification text not null,
  created_at timestamp with time zone not null default current_timestamp,
  updated_at timestamp with time zone not null default current_timestamp,
  constraint uq_authorizations_tenant_external unique (tenant_id, authorization_id)
);

create table if not exists authorization_procedures (
  id bigint generated by default as identity primary key,
  authorization_pk bigint not null references authorizations(id),
  tenant_id uuid not null,
  procedure_code text not null,
  constraint uq_authorization_procedures unique (authorization_pk, procedure_code)
);

create table if not exists outbox_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null,
  tenant_id uuid not null,
  aggregate_type text not null,
  aggregate_id uuid not null,
  event_type text not null,
  event_version integer not null,
  correlation_id uuid not null,
  payload text not null,
  occurred_at timestamp with time zone not null,
  published_at timestamp with time zone,
  constraint uq_outbox_event_id unique (event_id)
);

create table if not exists idempotency_keys (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  idempotency_key text not null,
  request_hash text not null,
  authorization_id uuid,
  response_snapshot text,
  created_at timestamp with time zone not null default current_timestamp,
  constraint uq_idempotency_tenant_key unique (tenant_id, idempotency_key)
);

create table if not exists audit_trail (
  id bigint generated by default as identity primary key,
  audit_id uuid not null,
  tenant_id uuid not null,
  aggregate_type text not null,
  aggregate_id uuid not null,
  action text not null,
  actor text not null,
  correlation_id uuid not null,
  metadata text,
  created_at timestamp with time zone not null default current_timestamp,
  constraint uq_audit_id unique (audit_id)
);
