create table if not exists operator_dispatches (
  id bigint generated by default as identity primary key,
  dispatch_id uuid not null,
  tenant_id uuid not null,
  authorization_id uuid not null,
  operator_code text not null,
  dispatch_type text not null,
  technical_status text not null,
  attempt_count integer not null default 0,
  external_protocol text,
  created_at timestamp with time zone not null default current_timestamp,
  updated_at timestamp with time zone not null default current_timestamp,
  constraint uq_operator_dispatch_id unique (dispatch_id),
  constraint fk_operator_dispatch_authorization
    foreign key (tenant_id, authorization_id) references authorizations(tenant_id, authorization_id)
);

create index if not exists idx_operator_dispatch_auth
  on operator_dispatches (tenant_id, authorization_id, created_at desc);
