alter table outbox_events
  add column if not exists publish_attempts integer not null default 0;

alter table outbox_events
  add column if not exists last_error text;

alter table outbox_events
  add column if not exists dead_letter_at timestamp with time zone;

create index if not exists idx_outbox_pending
  on outbox_events (occurred_at, published_at, dead_letter_at);

create table if not exists outbox_dead_letters (
  id bigint generated by default as identity primary key,
  outbox_event_id bigint not null unique references outbox_events(id),
  event_id uuid not null,
  tenant_id uuid not null,
  event_type text not null,
  payload text not null,
  failure_reason text not null,
  failed_at timestamp with time zone not null default current_timestamp
);
