create table if not exists tiss_guides (
  id bigint generated by default as identity primary key,
  tiss_guide_id uuid not null,
  tenant_id uuid not null,
  authorization_id uuid not null,
  tiss_version text not null,
  xml_content text not null,
  xml_hash text not null,
  validation_status text not null,
  validation_report text,
  created_at timestamp with time zone not null default current_timestamp,
  constraint uq_tiss_guides_tiss_guide_id unique (tiss_guide_id)
);

create index if not exists idx_tiss_guides_authorization
  on tiss_guides (tenant_id, authorization_id, created_at desc);
